name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  godot_version:
    description: 'the necessary version of godot'
    required: true
    default: '3.4.4-stable'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
