name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
    godot_version:
        description: 'the necessary version of godot'
        required: true
        default: '3.4.4-stable'
    use_mono:
        description: 'whether to use the mono builds'
        required: true
        default: 'false'
    base_dir:
        description: 'base directory'
        required: true
        default: './'

outputs:
    artifacts:
        description: Comma separated list of generated artifacts

runs:
    using: 'node16'
    main: 'dist/index.js'
