on:
    push:
        branches:
            - main
jobs:
    export_game:
        runs-on: ubuntu-latest
        name: Export game
        steps:
            - name: checkout
              uses: actions/checkout@v2.0.0
            - name: Read version.txt
              id: version
              uses: juliangruber/read-file-action@v1
              with:
                path: ./examples/godot_3.4.4_mono/version.txt
            - name: export godot
              id: godot
              uses: manuel3108/github-godot-export@main
              with:
                  godot_version: 3.4.4-stable
                  use_mono: true
                  base_dir: ./examples/godot_3.4.4_mono/
            - name: create release
              uses: ncipollo/release-action@v1
              with:
                artifacts: ${{ steps.godot.outputs.artifacts }}
                generateReleaseNotes: true
                tag: ${{ steps.version.outputs.content }}
                token: ${{ secrets.GITHUB_TOKEN }}

