on:
    push:
        branches:
            - main
jobs:
    export_game:
        runs-on: ubuntu-latest
        name: Export game
        steps:
            - name: checkout
              uses: actions/checkout@v2.0.0
            - name: export godot
              uses: manuel3108/github-godot-export@main
              with:
                  godot_version: 3.4.4-stable
                  use_mono: true
                  base_dir: ./examples/godot_3.4.4_mono/
                  export_templates: '["Linux/X11"]'
            # - name: Setup tmate session
            #   uses: mxschmitt/action-tmate@v3
